HELLO_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_PROJECT_PATH)/example/hello/src
SCRIPT_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_PROJECT_PATH)/example/script/src
LIBFOO_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_PROJECT_PATH)/example/libfoo/src
